name: Code Coverage

on:
  push:
    branches: [ code_coverage ]
  pull_request:
    branches: [ main ]

jobs:
  codecov:
    runs-on: macos-latest

    steps:
      - name: Delete .NET
        run: sudo rm -rf /usr/share/dotnet
      - name: Set environment variable
        run: export ADB_INSTALL_TIMEOUT=20
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          sdcard-path-or-size: 5000M
          ram-size: 4096M
          script: ./gradlew jacocoTestReport connectedCheck
      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports
      - name: Upload builds
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/outputs
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov
