name: Code Coverage

on:
  push:
    branches: [ mf_addJacoco ]
  pull_request:
    branches: [ mf_addJacoco ]

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run tests
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
        run: ./gradlew jacocoTestReport connectedCheck
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov