name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codecov:
    runs-on: macos-latest

    steps:
      - name: Delete .NET
        run: sudo rm -rf /usr/share/dotnet
      - name: Set environment variable
        run: export ADB_INSTALL_TIMEOUT=20
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Increase Heap
        run: /bin/sh -c \printf 'vm.heapsize=64' >> /Users/runner/.android/avd/test.avd/config.ini
      - name: Build with Gradle
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -partition-size 2048
          sdcard-path-or-size: 5000M
          ram-size: 8000M
          script: ./gradlew jacocoTestReport connectedCheck
      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports
      - name: Upload builds
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/outputs
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov
      - name: upload errors
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: app/build/reports
