name: Code Coverage

on:
  push:
    branches: [ mf_addJacoco ]
  pull_request:
    branches: [ mf_addJacoco ]

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Setup environment
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          sdcard-path-or-size: 2048M
        scripts: ./gradlew jacocoTestReport connectedCheck
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov