name: Code Coverage

on:
  push:
    branches: [ mf_addJacoco ]
  pull_request:
    branches: [ mf_addJacoco ]

jobs:
  codecov:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew jacocoTestReport
      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports
      - name: Upload builds
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/outputs
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov